###
@name=vezuka_ru_bot
POST {{host}}/api/v1/bots HTTP/1.1
Content-Type: application/json

{
    "botName": "vezuka.ru", 
    "botUserName": "vezuka_ru_bot", 
    "token": "1799278572:AAErkHAYqVlJdl2E8hONtJKgmcX2cLMGKKM"
}

###
@name=vezuka_buisness_bot
POST {{host}}/api/v1/bots HTTP/1.1
Content-Type: application/json

{
    "botName": "Vezuka Buisness", 
    "botUserName": "vezuka_buisness_bot ", 
    "token": "1929894844:AAECw90tr1raKOigeWYhC-tWBQt66Wo-GqY"
}

###
POST {{host}}/api/v1/msg/da02fde58373b002 HTTP/1.1
Content-Type: application/json

{
    "msg": "Проверка звука!"
}

###
POST {{host}}/api/v1/msg/8e252cfcc969fb99 HTTP/1.1
Content-Type: application/json

{
    "msg": "Проверка *связи* \\!",
    "type": "markdown"
}